### ISSUE TITLE
error on bash run/test_voc_first.sh

### ISSUE THREAD

**Issue by MonsterLWR** [YoungXIAO13/FewShotDetection#29]
i got these error when using ` bash run/test_voc_first.sh`
```
(FSdetection) jsi@jsi-GS75-Stealth-9SE:~/PycharmProjects/FewShotDetection$ bash run/test_voc_first.sh 
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections, vis_detections_label_only
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaRegisterFatBinaryEnd
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections, vis_detections_label_only
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaRegisterFatBinaryEnd
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections, vis_detections_label_only
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaRegisterFatBinaryEnd
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections, vis_detections_label_only
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaRegisterFatBinaryEnd
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections, vis_detections_label_only
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /home/jsi/PycharmProjects/FewShotDetection/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaRegisterFatBinaryEnd

```

here is my enviroment, which is pytorch 0.4.0 and cuda8.0. don't know whats going wrong:
```
(FSdetection) jsi@jsi-GS75-Stealth-9SE:~/PycharmProjects/FewShotDetection$ conda list
# packages in environment at /home/jsi/anaconda3/envs/FSdetection:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2020.12.8            h06a4308_0    defaults
certifi                   2020.12.5        py36h06a4308_0    defaults
cffi                      1.14.4           py36h261ae71_0    defaults
cuda80                    1.0                  h205658b_0    pytorch
cudatoolkit               8.0                           3    defaults
cython                    0.29.21          py36h2531618_0    defaults
easydict                  1.9                      pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0    defaults
intel-openmp              2020.2                      254    defaults
jpeg                      9b                   h024ee3a_2    defaults
lcms2                     2.11                 h396b838_0    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
lz4-c                     1.9.2                heb0550a_3    defaults
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py36he8ac12f_0    defaults
mkl_fft                   1.2.0            py36h23d657b_0    defaults
mkl_random                1.1.1            py36h0573a6f_0    defaults
ninja                     1.10.2           py36hff7bd54_0    defaults
numpy                     1.19.2           py36h54aff64_0    defaults
numpy-base                1.19.2           py36hfa32c7d_0    defaults
olefile                   0.46                     py36_0    defaults
openssl                   1.0.2u               h7b6447c_0    defaults
pandas                    0.25.3                   pypi_0    pypi
pillow                    8.1.0            py36he98fc37_0    defaults
pip                       20.3.3           py36h06a4308_0    defaults
pycparser                 2.20                       py_2    defaults
python                    3.6.0                         0    defaults
pytorch                   0.4.0           py36_cuda8.0.61_cudnn7.1.2_1    pytorch
pytz                      2020.5                   pypi_0    pypi
readline                  6.2                           2    defaults
scipy                     1.2.0                    pypi_0    pypi
setuptools                51.1.2           py36h06a4308_3    defaults
six                       1.15.0           py36h06a4308_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
torchvision               0.2.1                    py36_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.5                h9ceee32_0    defaults

```

**Comment by renqiqi** [comment]
hava you solved this problem? Thanks!

**Comment by MonsterLWR** [comment]
i did not solve it, but i guess it's because i compile .cu files with a different version of cuda.

**Comment by MonsterLWR** [comment]
saddly my gpu does not support cuda8.0, so i can not test it.
