### ISSUE TITLE
train custom datasets show error!

### ISSUE THREAD

**Issue by lihuikenny** [YoungXIAO13/FewShotDetection#37]
There is such an error when training your own data set, but there is no problem in checking my own data：
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    roidb = filter_class_roidb_flip(roidb, 0, imdb, base_num)
  File "/home/map/lihui44/FewShotDetection/lib/roi_data_layer/roidb.py", line 162, in filter_class_roidb_flip
    assert (boxes[:, 2] >= boxes[:, 0]).all()

If I comment out assert, another error will appear, Do you know the reason?

**Comment by lihuikenny** [comment]
pretrained model don`t doneload，could you please privided another link to me? thanks
