### ISSUE TITLE
No module named 'model.utils.cython_bbox'

### ISSUE THREAD

**Issue by SimonOuellette35** [YoungXIAO13/FewShotDetection#42]
Hi,

I followed the instructions (I think) and as I try running: bash run/finetune_voc_first.sh, I get the following error trace:

Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from roi_data_layer.roidb import combined_roidb, rank_roidb_ratio, filter_class_roidb_flip, clean_roidb
  File "/home/lab/FSDetView/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/lab/FSDetView/lib/datasets/factory.py", line 15, in <module>
    from datasets.coco import coco
  File "/home/lab/FSDetView/lib/datasets/coco.py", line 10, in <module>
    from datasets.imdb import imdb
  File "/home/lab/FSDetView/lib/datasets/imdb.py", line 14, in <module>
    from model.utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'model.utils.cython_bbox'

It might be worth noting as well that the previous error was complaining that data/cache doesn't exist, which I circumvented by commenting out the os.list("data/cache") line in _init_paths.py.

**Comment by Vrishabhdhwaj** [comment]
Hello there, were you able to resolve this error?

**Comment by cccxiaozhe** [comment]
from model.rpn.bbox_transform import bbox_overlaps
好像改成这样就可以了
